### ISSUE TITLE
npm 安装的vue-better-slider 与你的源码文件 vue-better-slider 不一致

### ISSUE THREAD

**Issue by mraing** [songhaoreact/vue-better-slider#2]
`npm install  vue-better-slider --save` 安装后，我在 `node_modules `文件夹目录中的查看了安装后的`vue-better-slide`文件夹，发现里面有文件缺失，跟你的源码有差异。导致项目运行不成功。

解决方案：我把你的源码`vue-better-slider`中的文件夹**替换**掉 npm 安装后的`vue-better-slider`文件目录就可以了。

希望对后来的朋友有帮助。

谢谢大佬提供的轮播图插件，很简洁轻便，thk~

**Comment by openfe-openfe** [comment]
更新了readme
